[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100_000

remappings = [
  "lib/composable-cow:safe/=lib/composable-cow/lib/safe/contracts/",
  "lib/composable-cow:@openzeppelin/=lib/openzeppelin/contracts/",
  "lib/composable-cow:@openzeppelin/contracts/=lib/openzeppelin/contracts/",
  "@v4-core/=lib/v4-core/src/",
  "@v4-core-test/=lib/v4-core/test/", 
  "@src/=src/",
  "@forks/=forks/",
  "lib/composable-cow:cowprotocol/=lib/composable-cow/lib/cowprotocol/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
